## Numpy Array operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing:  8


In [7]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[0])
print("Entire column: ", arr_2d[:,2])

Specific element:  6
Entire row:  [1 2 3]
Entire column:  [3 6 9]


## Sorting

In [11]:
unsorted = np.array([1,4,5,3,9,7,5,7,10,8])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array: ", np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [ 1  3  4  5  5  7  7  8  9 10]
Sorted 2D array:  [[1 1]
 [2 2]
 [3 3]]


## Filter

In [3]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ", even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [14]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [17]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [4]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing data

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]
