## Numpy arrays and basics
learn about numpy with chai aur code

In [2]:
import numpy as np

## creating arrays with list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array : ", arr_2d)

1D array:  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [6]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication: ", np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)



Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.20607233047485352

 Numpy operation time:  0.023939847946166992


##creating array from scratch

In [14]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("Full array of 7: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0,11, 2)
print("squence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array of 7: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.65219238 0.75338199 0.62357692]
 [0.55579608 0.13867755 0.36146203]]
squence array: 
 [ 0  2  4  6  8 10]


##Vector, Metrix and Tensor

In [17]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64
