## Additional Advance operations

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

In [6]:
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)

In [11]:
loaded_array1 = np.load('array1.npy')
print("Loaded Array 1: ", loaded_array1)

loaded_array2 = np.load('array2.npy')
print("Loaded Array 2: \n", loaded_array2)

loaded_array3 = np.load('array3.npy')
print("Loaded Array 3: \n", loaded_array3)

Loaded Array 1:  [1 2 3 4 5]
Loaded Array 2: 
 [[0.29527469 0.86352127 0.0504203 ]
 [0.03156165 0.10973552 0.39647031]
 [0.69784892 0.13769589 0.73846533]]
Loaded Array 3: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
try:
    logo = np.load('numpy-logo.npy')

    # Display
    plt.figure(figsize=(10, 5))
    plt.plot(121)
    
except FileNotFoundError:
    print("Numpy logo file not found")